### Lesson 3

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

__Решение__

При перемножении количество столбцов левой матрицы должно совпадать с количеством строк правой матрицы.

а) $A\cdot B$ и $B\cdot A$ не определены.

б) $A\cdot B$ определено, размерность матрицы $2 \times 3$. $B\cdot A$ не определено.

в) $A\cdot B$ определено, размерность матрицы $8 \times 8$. $B\cdot A$ также определено, размерность - $3 \times 3$.

г) $A\cdot B$ и $B\cdot A$ определены. Размерности матриц - $4 \times 4$.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__

$$A + B = 
    \begin{pmatrix}
    1 & -2\\ 
    3 & 0
    \end{pmatrix} + \begin{pmatrix}
    4 & -1\\ 
    0 & 5
    \end{pmatrix} = \begin{pmatrix}
    5 & -3\\ 
    3 & 5
    \end{pmatrix}
    $$

$$A \cdot B = 
    \begin{pmatrix}
    1 & -2\\ 
    3 & 0
    \end{pmatrix} \cdot \begin{pmatrix}
    4 & -1\\ 
    0 & 5
    \end{pmatrix} = \begin{pmatrix}
    4 & -11\\ 
    12 & -3
    \end{pmatrix}
    $$

$$B \cdot A = 
    \begin{pmatrix}
    4 & -1\\ 
    0 & 5
    \end{pmatrix} \cdot \begin{pmatrix}
    1 & -2\\ 
    3 & 0
    \end{pmatrix} = \begin{pmatrix}
    1 & -8\\ 
    15 & 0
    \end{pmatrix}
    $$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A + B\n{A + B}')
print(f'Матрица A*B\n{np.dot(A, B)}')
print(f'Матрица B*A\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A + B
[[ 5 -3]
 [ 3  5]]
Матрица A*B
[[  4 -11]
 [ 12  -3]]
Матрица B*A
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__

$3 \cdot \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}+(-2)\cdot \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}+4\cdot \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = 
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} +
\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} +
\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$

In [3]:
A = np.array([[1, 7], [3,-6]])
B = np.array([[0, 5], [2,-1]])
C = np.array([[2,-4], [1, 1]])
D = 3*A + (-2)*B + 4*C
D

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__Решение__

$$  AA^{T} = 
    \begin{pmatrix}
    4 & 1\\ 
    5 & -2\\ 
    2 & 3
    \end{pmatrix}
    \cdot
    \begin{pmatrix}
    4 & 5 & 2\\ 
    1 & -2 & 3
    \end{pmatrix}
    =
    \begin{pmatrix}
    4\cdot4 + 1\cdot 1 & 4\cdot5 - 1\cdot 2 & 4\cdot2 + 1\cdot 3\\ 
    5\cdot4 - 2\cdot 1 & 5\cdot5 + 2\cdot 2 & 5\cdot2 - 2\cdot 3\\ 
    2\cdot4 + 3\cdot 1 & 2\cdot5 - 3\cdot 2 & 2\cdot2 + 3\cdot 3
    \end{pmatrix}
    =
    \begin{pmatrix}
    17 & 18 & 11\\ 
    18 & 29 & 4\\ 
    11 & 4 & 13
    \end{pmatrix}
    $$

$$
    A^{T}A = 
    \begin{pmatrix}
    4 & 5 & 2\\ 
    1 & -2 & 3
    \end{pmatrix}
    \cdot
    \begin{pmatrix}
    4 & 1\\ 
    5 & -2\\ 
    2 & 3
    \end{pmatrix}
    =
    \begin{pmatrix}
    4\cdot4 + 5\cdot 5 + 2 \cdot 2 & 4\cdot1 - 5\cdot 2 + 2 \cdot 3\\ 
    1\cdot4 - 2\cdot 5 + 3 \cdot 2 & 1\cdot1 + 2\cdot 2 + 3 \cdot 3
    \end{pmatrix}
    =
    \begin{pmatrix}
    45 & 0\\ 
    0 & 14
    \end{pmatrix}
    $$

In [4]:
A = np.array([[4, 1], [5,-2], [2, 3]])
print(f'A * A_T =\n{A.dot(A.T)}\n')
print(f'A_T * A =\n{A.T.dot(A)}')

A * A_T =
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A_T * A =
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [5]:
def matrixmulti(M1, M2):
    r1 = len(M1)    # строк в первой матрице
    c1 = len(M1[0]) # столбцов в 1-ой матрице
    r2 = len(M2)    # строк во 2-ой матрице
    c2 = len(M2[0]) # столбцов во 2-ой матрице
    if c1 != r2:
        print('Матрицы не могут быть перемножены!')
    else:
        S = 0
        T = []
        M3= []
        for i in range(0,r1):
            for j in range(0,c2):
                for k in range(0,c1):
                    S += M1[i][k] * M2[k][j]
                T.append(S)
                S = 0
            M3.append(T)
            T=[]
    return np.array(M3)

In [6]:
matrixmulti(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [7]:
matrixmulti(A.T, A)

array([[45,  0],
       [ 0, 14]])

### Lesson 4

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

__Решение__

a) $$|A| = sin^2x + cos^2x = 1$$

б) $$|A| = 4 \cdot 5 \cdot 9 = 180$$

в) Т.к. у матрицы линейно-зависимые строки и столбцы, определитель должен быть равен 0.   
   
$$|A| = 1 \cdot 
\begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix}- 2 \cdot
\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix}+ 3 \cdot
\begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = (5\cdot 9 - 6\cdot 8) - 2\cdot (4\cdot 9 - 6\cdot 7) + 3\cdot (4\cdot 8 - 5\cdot 7) = -3 + 12 - 9 = 0
$$

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Определитель матрицы А = {np.linalg.det(A):.1f}')

Определитель матрицы А = 0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__

а) $det(A^2) = det(A) \cdot det(A) = 4\cdot 4 = 16$

б) $det(A^T) = det(A) = 4$

в) $det(2A) = 2^n \cdot det(A) = 2^n \cdot 4$, где $n$ - количество строк матрицы $A$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Решение__

Вычтем из второй строки первую строку, умноженную на (-2):   
   
$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = 
\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix} \Rightarrow |A| = 0
$$ Определитель равен 0 $\Rightarrow$ матрица вырожденная

In [20]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Определитель матрицы А = {np.linalg.det(A):.1f}')

Определитель матрицы А = 0.0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение__

Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:
$$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}$$
Из второй строки вычтем первую:
$$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & 2
\end{pmatrix}$$
Ранг матрицы = 2

In [24]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
rank = np.linalg.matrix_rank(A)

print(f'Ранг матрицы A = {rank}')

Ранг матрицы A = 2


б) Третья строка является суммой первой и второй строк, а значит, ее можно отбросить:
$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$
   
Определитель минора третьего порядка не равен 0 $\Rightarrow$ Матрица имеет ранг 3

In [25]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
rank = np.linalg.matrix_rank(A)

print(f'Ранг матрицы A = {rank}')

Ранг матрицы A = 3
