__1. Найти с помощью NumPy SVD для матрицы__

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1,  2, 0],
              [0,  0, 5],
              [3, -4, 2],
              [1,  6, 5],
              [0,  1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [3]:
U, s, W = np.linalg.svd(A)
# Транспонируем матрицу W
V = W.T

In [4]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [5]:
V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [6]:
s

array([8.82, 6.14, 2.53])

In [7]:
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [8]:
# Матрица U ортогональна
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1. -0. -0.]
 [ 0. -0. -0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [9]:
# Матрица V ортогональна
print(np.dot(V.T, V))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Проверка SVD разложения
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


__2. Для матрицы из предыдущего задания найти:__

    а) евклидову норму;
    
    б) норму Фробениуса.

In [11]:
# а) Евклидова норма
print(f'Евклидова норма матрицы А = {D[0,0]:.3f}')

Евклидова норма матрицы А = 8.825


In [12]:
np.linalg.norm(A, ord=2)

8.824868854820442

In [13]:
# б) Норма Фробениуса
print(f'Норма Фробениуса матрицы А = {np.sqrt(np.sum(D**2)):.3f}')

Норма Фробениуса матрицы А = 11.045


In [14]:
np.linalg.norm(A, ord='fro')

11.045361017187261

In [15]:
np.linalg.norm(A)

11.045361017187261

По умолчанию для матриц возвращается норма Фробениуса