__1.__ Исследовать на линейную зависимость:
$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$

__Решение__   
   
$f_{1}(x)= e^{x} = -f_{2}(x) + f_{3}(x) - f_{4}(x) = (-1) + x + 1 - x + e^{x} = e^{x}$   
   
Один из векторов является линейной комбинацией трёх остальных. Из этого следует, что векторы линейно зависимы.

---

__2.__ Исследовать на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}.$$

__Решение__    

Для того, чтобы некоторое множество элементов линейного пространства было линейно зависимым, необходимо и достаточно, чтобы один из этих элементов являлся линейной комбинацией остальных.   
   
Выразим один из векторов через другие:
$$f_{4}(x)=(x+1)^{2} = x^{2}+2x+1 = f_{3}(x) + 2 \cdot f_{2}(x) + 0.5 \cdot f_{1}(x) = x^{2} + 2x + 1 $$   
   
Векторы линейно зависимы.

---

__3.__ Найти координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

__Решение__    
   
$x = 0.5 \cdot b_{1} + 1 \cdot b_{2} + 3 \cdot b_{3}$   
$x = (0.5, 1, 3)$

In [1]:
import numpy as np

In [2]:
x = np.array([2,3,5])
b1 = np.array([0,0,10])
b2 = np.array([2,0,0])
b3 = np.array([0,1,0])

In [3]:
V = np.array([b1, b2, b3]).T
V

array([[ 0,  2,  0],
       [ 0,  0,  1],
       [10,  0,  0]])

In [4]:
A = np.linalg.inv(V)
A

array([[0. , 0. , 0.1],
       [0.5, 0. , 0. ],
       [0. , 1. , 0. ]])

In [5]:
L = np.dot(A, x)
L

array([0.5, 1. , 3. ])

---

__4.__ Найти координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

   а) в базисе $1$, $x$, $x^{2}$;

   б) в базисе $x^{2}$, $x-1$, $1$.

__Решение__   

а) Координаты, которые удовлетворяют условию в базисе $1$, $x$, $x^{2}$:   
$$3x^{2}-2x+2 = 1 \cdot 2 + x \cdot (-2) + x^{2} \cdot 3$$
$(2, -2, 3)$

б) Координаты, которые удовлетворяют условию в базисе $x^{2}$, $(x-1)$, $1$:   
$$3x^{2}-2x+2 = x^2 \cdot 3 + (x-1) \cdot (-2) + 1 \cdot 0$$
$(3, -2, 0)$

---

__5.__ Установить, является ли линейным подпространством:

а) совокупность всех векторов трехмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;
    
б) все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$.

__Решение__   
   
а) Возможные варианты:   
- первая координата равна нулю $(0, b, c)$   
- вторая координата равна нулю $(d, 0, f)$   
- обе первые координаты равны нулю $(0, 0, g)$

Проверим случай, когда у первого вектора первая координата равна нулю, а у второго - вторая:   
$(0, b, c) + (d, 0, f) = (d, b, c+f)$   
Полученный вектор не принадлежит указанному множеству всех векторов, то есть данное множество не является подпространством линейного пространства $\mathbb{R}^{3}$.

б) Результаты операций $\ u+v$ и $\ \alpha\cdot u$ также будут являться линейными комбинациями заданных векторов $\{u_{1}, u_{2}, ..., u_{n}\} \implies$   
Все векторы, являющиеся линейными комбинациями данных векторов $\{u_{1}, u_{2}, ..., u_{n}\}$ будут являться линейным подпространством.

### Lesson 2

__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [6]:
x = np.array([0, -3, 6])
y = np.array([-4,7,9])
print(f'1. Скалярное произведение x и y = {np.dot(x, y)}')

1. Скалярное произведение x и y = 33


In [7]:
x = np.array([ 7,-4,  0, 1])
y = np.array([-3, 1, 11, 2])
print(f'2. Скалярное произведение x и y = {np.dot(x, y)}')

2. Скалярное произведение x и y = -23


__2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

In [8]:
from numpy.linalg import norm
import math

In [9]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

In [10]:
print(f'Евклидова норма вектора a: {norm(a, ord=2)}')
print(f'Евклидова норма вектора b: {norm(b, ord=2)}')

Евклидова норма вектора a: 6.0
Евклидова норма вектора b: 13.0


In [13]:
def angle(a, b):
    return math.degrees(np.arccos(np.dot(a,b) / norm(a) / norm(b)))

In [14]:
print(f'Угол между векторами : {angle(a,b):.2f}°')

Угол между векторами : 26.18°


__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?

а) Проверим, удовлетворяет ли произведение длин векторов аксиомам Евклидова пространства:   
1) $\left|x\right|\cdot\left|y\right| = \left|y\right|\cdot\left|x\right|$ - выполняется   
2) $(\lambda \cdot \left|x\right|)\cdot\left|y\right|= \lambda \cdot (\left|x\right|\cdot\left|y\right|)$ - выполняется   
3) $\left|x_{1}\right|\cdot\left|y\right| + \left|x_{2}\right|\cdot\left|y\right|= (\left|x_{1}\right|+\left|x_{2}\right|)\cdot\left|y\right|$,   
но $\left|x_{1}\right| + \left|x_{2}\right| \geq \left|x_{1}+x_{2}\right|$, так как $(\sqrt{\sum_{i}|x_{1i}|^{2}}+\sqrt{\sum_{i}|x_{2i}|^{2}}) \geq \sqrt{\sum_{i}|x_{1i}+x_{2i}|^{2}}$   
=> $(x_{1}+x_{2},y)\leq(x_{1},y)+(x_{2},y)$  3-я аксиома не выполняется и, следовательно, линейное пространство не будет Евклидовым.

б) Проверим, выполняются ли аксиомы принадлежности к Евклидову пространству, если $(x, y) = 3 \cdot \left|x\right|\cdot\left|y\right|cos\alpha.$

1) $(x,y)=(y,x)$ - выполняется   
2) $(\lambda x, y)=\lambda(x, y)$ - выполняется   
3) $(x_{1},y)+(x_{2},y)=3 \cdot \left|x_{1}\right|\cdot\left|y\right|cos\alpha_{1} +3 \cdot \left|x_{2}\right|\cdot\left|y\right|cos\alpha_{2}=3(\left|x_{1}\right|cos\alpha_{1}+\left|x_{2}\right|cos\alpha_{2})\left|y\right|= 3\cdot(\left|x_{1}+x_{2}\right|cos\alpha)\left|y\right|= (x_{1}+x_{2},y) $ - выполняется   
4) $(x, x)\geq0$, причем $(x,x)=0\Leftrightarrow x=0$ - выполняется   
Аксиомы выполняются => линейное пространство будет Евклидовым.

__4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

а) Базисом не являются, т.к. базис в линейном пространстве $\mathbb{R}^{3}$ должен содержать 3 вектора.

б) Образуют ортонормированный базис

In [18]:
x = [1/np.sqrt(2), -1/np.sqrt(2), 0]
y = [1/np.sqrt(2), 1/np.sqrt(2), 0]
z = [0, 0, 1]
print(f'Норма x: {norm(x):.2f}')
print(f'Норма y: {norm(y):.2f}')
print(f'Норма z: {norm(z):.2f}')
print(f'Угол <x,y> {angle(x, y):.1f}°')
print(f'Угол <x,z> {angle(x, z):.1f}°')
print(f'Угол <y,z> {angle(y, z):.1f}°')

Норма x: 1.00
Норма y: 1.00
Норма z: 1.00
Угол <x,y> 90.0°
Угол <x,z> 90.0°
Угол <y,z> 90.0°


г) Базисом не являются

In [19]:
x = [1/2, -1/2, 0]
y = [0, 1/2, 1/2]
z = [0, 0, 1]
print(f'Норма x: {norm(x):.2f}')
print(f'Норма y: {norm(y):.2f}')
print(f'Норма z: {norm(z):.2f}')
print(f'Угол <x,y> {angle(x, y):.1f}°')
print(f'Угол <x,z> {angle(x, z):.1f}°')
print(f'Угол <y,z> {angle(y, z):.1f}°')

Норма x: 0.71
Норма y: 0.71
Норма z: 1.00
Угол <x,y> 120.0°
Угол <x,z> 90.0°
Угол <y,z> 45.0°


г) Образуют ортонормированный базис

In [20]:
x = [1, 0, 0]
y = [0, 1, 0]
z = [0, 0, 1]
print(f'Норма x: {norm(x):.2f}')
print(f'Норма y: {norm(y):.2f}')
print(f'Норма z: {norm(z):.2f}')
print(f'Угол <x,y> {angle(x, y):.1f}°')
print(f'Угол <x,z> {angle(x, z):.1f}°')
print(f'Угол <y,z> {angle(y, z):.1f}°')

Норма x: 1.00
Норма y: 1.00
Норма z: 1.00
Угол <x,y> 90.0°
Угол <x,z> 90.0°
Угол <y,z> 90.0°
