__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__Решение__

Cоставим и решим характеристическое уравнение:   

$\left(\begin{array}{cc}
{-1-\lambda} & {-6}\\ 
{2} & {6-\lambda}
\end{array}\right) = 0$

$(-1 -\lambda)\cdot (6 - \lambda) + 12 = 0$   
$\lambda^2 - 5\lambda + 6 = 0$   
$\lambda_1 = 2, \:\: \lambda_2 = 3$

1) $\lambda_1 = 2$
    
$   \left(\begin{array}{cc}
    {-1 - 2} & {-6}\\ 
    {2} & {6 -2}
    \end{array}\right)$
$   \left(\begin{array}{c}
    x_{1}\\ 
    x_{2}
    \end{array}\right)=0$
    
$   \left(\begin{array}{cc}
    {-3} & {-6}\\ 
    {2} & {4}
    \end{array}\right)$
$   \left(\begin{array}{c}
    x_{1}\\ 
    x_{2}
    \end{array}\right)=0$
    
$x_1 + 2 x_2 = 0$
    
Собственный вектор $(2, -1)$

2) $\lambda_2 = 3$

$   \left(\begin{array}{cc}
    {-1 - 3}& {-6}\\ 
    {2} & {6 -3}
    \end{array}\right) $
$   \left(\begin{array}{c}
    {x_{1}}\\ 
    {x_{2}}
    \end{array}\right)=0 $
    
$   \left(\begin{array}{cc}
    {-4}& {-6}\\ 
    {2} & {3}
    \end{array}\right) $
$   \left(\begin{array}{c}
    {x_{1}}\\ 
    {x_{2}}
    \end{array}\right)=0 $
    
$   2 x_1 + 3 x_2 = 0 $
    
Собственный вектор $(3, -2)$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

__Решение__

$\left(\begin{array}{cc}
{-1-\lambda} & {0}\\ 
{0} & {-1-\lambda}
\end{array}\right) = 0    \Rightarrow (-1-\lambda)^{2}=0  \Rightarrow \lambda=(-1)$ (собственное значение)

_Собственный вектор_ оператора $\textbf{A}$ — это такой ненулевой вектор, действие оператора на который сводится к умножению его на число: $\textbf{A}x=\lambda x.$

$\forall (x_1, x_2) :
\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = 
(-1)\cdot 
\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}$

__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

__Решение__

Решим уравнение относительно $\lambda$: $\textbf{A}x=\lambda x$

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix} = 
\lambda \cdot 
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$

$\begin{cases}
    1 + 1 = \lambda \\
    -1 + 3 = \lambda
  \end{cases} \Rightarrow $   
$\lambda_1 = 2 $   
$\lambda_2 = 2 $

Вектор $(1, 1)$ является собственным для матрицы $\textbf{A}$. Собственное значение $\lambda = 2$.

In [3]:
a = np.array([[ 1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 2.]

Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix} =
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}$

$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$

Система несовместна $\Rightarrow$ вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора $\textbf{A}$.

In [4]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
