### Урок 6

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__Решение__

Запишем расширенную матрицу системы:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 &  1 \\ 
1 & 1 & -3 &  1
\end{matrix}\right|
\begin{matrix}
 0\\ 
-2\\
 4
\end{matrix}
\end{pmatrix}.$$

Вычтем из второй строки удвоенную первую и из третьей первую:

$$\begin{pmatrix}
\left.\begin{matrix}
1 &  1 & -1 & -2\\ 
0 & -1 &  1 &  5 \\ 
0 &  0 & -2 &  3
\end{matrix}\right|
\begin{matrix}
 0\\ 
-2\\
 4
\end{matrix}
\end{pmatrix}.$$

Получившаяся матрица соответствует системе:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~~~-x_{2}+x_{3}+5x_{4}=-2, \\
~~~~~~~~~~~-2x_{3}+3x_{4}=4
\end{cases}$$

Число уравнений меньше числа неизвестных, следовательно система имеет бесконечное число решений.   
Найдём общее решение системы, приняв $x_4=c$  
   
$-2x_3 +3c = 4 \; \Leftrightarrow \; x_3 = \frac{3c-4}{2}=1.5c-2$   
$-x_2 + 1.5c - 2 + 5c = -2 \; \Leftrightarrow \; x_2 = 6.5c$   
$x_1 + 6.5c - (1.5c-2) - 2c = 0 \; \Leftrightarrow \; x_1 = -3c - 2$

Частное решение при $c=0$:   
   
$ x_1 = -2; x_2 = 0; x_3 = -2; x_4=0$

In [1]:
import numpy as np

In [2]:
def solving_sle(A, b, n):
    rank_A = np.linalg.matrix_rank(A)
    rank_Ab = np.linalg.matrix_rank(np.hstack((A, b)))
    if  rank_A == rank_Ab == n:
        return 'Cистема совместна и определена. Имеет единственное решение'
    elif (rank_A == rank_Ab) and (rank_A < n):
        return 'Cистема совместна и имеет бесконечное количество решений'
    elif rank_A < rank_Ab:
        return 'Cистема несовместна. Не имеет решений.'

In [3]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4]).reshape(-1, 1)
n = 4  # число неизвестных
print(solving_sle(A, b, n))

Cистема совместна и имеет бесконечное количество решений


__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

__Решение__

In [4]:
# а)
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0]).reshape(-1, 1)
print(solving_sle(A, b, 3))

Cистема совместна и определена. Имеет единственное решение


In [5]:
# б)
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5]).reshape(-1, 1)
print(solving_sle(A, b, 3))

Cистема несовместна. Не имеет решений.


In [6]:
# в)
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2]).reshape(-1, 1)
print(solving_sle(A, b, 3))

Cистема совместна и имеет бесконечное количество решений


__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__Решение__

In [7]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1]).reshape(-1, 1)
print(solving_sle(A, b, 4))

Cистема совместна и определена. Имеет единственное решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение__

Вычтем из второй строки первую строку, умноженную на 4:   
   
$\begin{pmatrix}
\left.\begin{matrix}
1 &  2 &  3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c
\end{matrix}
\end{pmatrix}$

Вычтем из третьей строки первую строку, умноженную на 7:   
   
$\begin{pmatrix}
\left.\begin{matrix}
1 &  2 &  3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}$

Прибавим из третьей строки вторую строку, умноженную на -2:   
$-2\cdot (b-4a) + (c-7a) = -2b + 8a + c - 7a = a - 2b + c$   
   
$\begin{pmatrix}
\left.\begin{matrix}
1 &  2 &  3\\ 
0 & -3 & -6\\ 
0 &  0 &  0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
a-2b+c
\end{matrix}
\end{pmatrix}$

Если $(a-2b+c) \neq 0$, то $rank \tilde A=3$, в то время как $rank A=2$. Это означает, что система в этом случае несовместна.

### Урок 7

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

__Решение__

In [8]:
A = np.array([[1, -2], [3, -4]])
b = np.array([[1, 7]]).reshape(-1, 1)
A1 = np.hstack((b, A[:,1].reshape(-1, 1)))
A2 = np.hstack((A[:,:-1].reshape(-1, 1), b))
print(f'{A}\n{b}\n{A1}\n{A2}')

[[ 1 -2]
 [ 3 -4]]
[[1]
 [7]]
[[ 1 -2]
 [ 7 -4]]
[[1 1]
 [3 7]]


In [9]:
det_A  = np.linalg.det(A)
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
x_1 = det_A1 / det_A
x_2 = det_A2 / det_A
print(f'x1 = {x_1:.2f}, x2 = {x_2:.2f}')

x1 = 5.00, x2 = 2.00


In [10]:
# Проверка
x1, x2 = np.linalg.solve(A, b)
print(f'x1 = {x1[0]:.2f}, x2 = {x2[0]:.2f}')

x1 = 5.00, x2 = 2.00


__1.__ Решить систему уравнений методом Крамера:   
б)   $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [11]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape(-1, 1)
A1 = np.hstack((b, A[:,1:]))
A2 = np.hstack((A[:,:1], b, A[:,-1:]))
A3 = np.hstack((A[:,:-1], b))
print(f'{A}\n{b}\n{A1}\n{A2}\n{A3}')

[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
[[10]
 [-2]
 [ 1]]
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]


In [12]:
det_A = np.linalg.det(A)
det_A1 = np.linalg.det(A1)
det_A2 = np.linalg.det(A2)
det_A3 = np.linalg.det(A3)
x_1 = det_A1 / det_A
x_2 = det_A2 / det_A
x_3 = det_A3 / det_A
print(f'x1 = {x_1:.2f}, x2 = {x_2:.2f}, , x3 = {x_3:.2f}')

x1 = 2.00, x2 = -1.00, , x3 = 1.00


In [13]:
# Проверка
x1, x2, x3 = np.linalg.solve(A, b)
print(f'x1 = {x1[0]:.2f}, x2 = {x2[0]:.2f}, x3 = {x3[0]:.2f}')

x1 = 2.00, x2 = -1.00, x3 = 1.00


__2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__Решение__

In [14]:
import scipy.linalg
np.set_printoptions(precision=2, suppress=True)
# а)
A = np.array([[1,2,4],[2,9,12],[3,26,30]])
P, L, U = scipy.linalg.lu(A)
L

array([[1.  , 0.  , 0.  ],
       [0.67, 1.  , 0.  ],
       [0.33, 0.8 , 1.  ]])

In [15]:
# Проверка
L.dot(U)

array([[ 3., 26., 30.],
       [ 2.,  9., 12.],
       [ 1.,  2.,  4.]])

In [16]:
# б)
A = np.array([[1,1,2,4],[2,5,8,9],[3,18,29,18],[4,22,53,33]])
P, L, U = scipy.linalg.lu(A)
L

array([[ 1.  ,  0.  ,  0.  ,  0.  ],
       [ 0.5 ,  1.  ,  0.  ,  0.  ],
       [ 0.75, -0.25,  1.  ,  0.  ],
       [ 0.25,  0.75, -0.17,  1.  ]])

In [17]:
# Проверка
L.dot(U)

array([[ 4., 22., 53., 33.],
       [ 2.,  5.,  8.,  9.],
       [ 3., 18., 29., 18.],
       [ 1.,  1.,  2.,  4.]])

__3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__Решение__

Матрица коэффициентов $A$ будет иметь вид

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}.$$

Начнем прямой ход метода Гаусса. Домножим первую строку на $\frac{11}{2}$ и вычтем ее из второго уравнения. При этом запишем в матрицу $L$ на место элемента $l_{21}$ значение $\frac{11}{2}$. Затем нам нужно вычесть из третьего уравнения первое, домноженное на $\frac{9}{2}$. Значит, в матрицу $L$ запишем $l_{31}=\frac{9}{2}$. 

Матрица коэффициентов будет иметь вид

$$\begin{pmatrix}
2 & 1 & -1 \\ 
0 & \frac{3}{2} & \frac{-23}{2} \\ 
0 & \frac{7}{2} & \frac{-19}{2}
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & l_{32} & 1
\end{pmatrix}.$$

Домножим вторую строку на $\frac{7}{3}$ и вычтем ее из третьего уравнения. При этом запишем в матрицу $L$ на место элемента $l_{32}$ значение $\frac{7}{3}$.

Матрица коэффициентов будет иметь вид:

$$\begin{pmatrix}
2 & 1 & -1 \\ 
0 & \frac{3}{2} & \frac{-23}{2} \\ 
0 & 0 & \frac{52}{3}
\end{pmatrix},$$

а матрица $L$ —

$$\begin{pmatrix}
1 & 0 & 0 \\ 
\frac{11}{2} & 1 & 0 \\ 
\frac{9}{2} & \frac{7}{3} & 1
\end{pmatrix}.$$

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
\frac{11}{2}y_{1}+y_{2}=-6, \\
\frac{9}{2}y_{1}+\frac{7}{3}y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1} = 1,$$
$$y_{2}=-\frac{23}{2},$$
$$y_{3}=-5 - \frac{9}{2} + \frac{23}{2}\cdot \frac{7}{3}=\frac{52}{3}.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3} = 1, \\
\frac{3}{2}x_{2}-\frac{23}{2}x_{3}=-\frac{23}{2}, \\
\frac{52}{3}x_{3}=\frac{52}{3}.
\end{cases}$$

$$x_{3}=1,$$
$$x_{2}=0,$$
$$x_{1}=-1.$$

Произведем проверку, подставив полученные значения переменных в исходную систему:

$$\begin{cases}
 2\cdot(-1)+1\cdot 0 +3\cdot 1 =  1, \\
11\cdot(-1)+7\cdot 0 +5\cdot 1 = -6, \\
 9\cdot(-1)+8\cdot 0 +4\cdot 1 = -5 .
\end{cases}$$

Таким образом, найденное решение верно.

---

__4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__Решение__

Матрица коэффициентов $A$ будет иметь вид

$$\begin{pmatrix}
 81 & -45 &  45 \\ 
-45 &  50 & -15 \\ 
 45 & -15 &  38
\end{pmatrix}.$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}\cdot l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )=\frac{10}{5}=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9}=3$$

Получили матрицу 

$$L = \begin{pmatrix}
 9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
 5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 &  5 & 2 \\ 
0 &  0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9\cdot y_{1}=531, \\
-5\cdot y_{1}+5\cdot y_{2}=-460, \\
5\cdot y_{1} +2\cdot y_{2}+3\cdot y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=\frac{-460+ (5\cdot 59)}{5}= -33,$$

$$y_{3}=\frac{193 - 5\cdot 59 -2\cdot (-33)}{3}=-\frac{36}{3} = -12$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=\frac{-33 - 2\cdot (-4)}{5}=\frac{-25}{5}= -5$$

$$x_{1}=\frac{59+5\cdot (-5) - 5\cdot (-4)}{9}=6.$$

Осуществим проверку, подставив полученные значения в исходную систему:

$$\begin{cases}
 81\cdot 6 - 45\cdot(-5) + 45\cdot(-4) = 486 + 225 - 180 = 531, \\
-45\cdot 6 + 50\cdot(-5) - 15\cdot(-4) = -270 - 250 + 60 = -460, \\
 45\cdot 6 - 15\cdot(-5) + 38\cdot(-4) =  270 + 75 - 152 = 193.
\end{cases}$$

---

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [62]:
def kramer(A,b):
    """ Решение линейных уравнений методом Крамера """
 
    n = len(A)
    a = list(zip(*A))

    det_a = np.linalg.det(a)
    if not det_a:
        raise RuntimeError("Система не имеет решения!")
 
    result = []
    for i in range(n):
        r = a[:]
        r[i] = list(b)
        result.append(round(np.linalg.det(r) / det_a,4))
    return result

In [63]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])
kramer(A,b)

[2.0, -1.0, 1.0]

In [64]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])
kramer(A,b)

[5.0, 2.0]